//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRP_COMPUNIT
    {
        public HRP_COMPUNIT()
        {
            this.PRP_ASSIGNMAS = new HashSet<PRP_ASSIGNMAS>();
            this.PRP_DISTTOFACT = new HashSet<PRP_DISTTOFACT>();
            this.PRP_MODULE = new HashSet<PRP_MODULE>();
            this.PRP_PRODMAS = new HashSet<PRP_PRODMAS>();
        }
    
        public byte COMPCD { get; set; }
        public string COMPNM { get; set; }
        public string SHORTNM { get; set; }
        public string COMPNMB { get; set; }
        public string ADDRS1 { get; set; }
        public string ADDRS2 { get; set; }
        public string ADDRSBG1 { get; set; }
        public string ADDRSBG2 { get; set; }
        public string PHONE { get; set; }
        public string MOBILNO { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public byte[] LOGO_IMAGE { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual ICollection<PRP_ASSIGNMAS> PRP_ASSIGNMAS { get; set; }
        public virtual ICollection<PRP_DISTTOFACT> PRP_DISTTOFACT { get; set; }
        public virtual ICollection<PRP_MODULE> PRP_MODULE { get; set; }
        public virtual ICollection<PRP_PRODMAS> PRP_PRODMAS { get; set; }
    }
}
