//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MER_ORDERDET
    {
        public MER_ORDERDET()
        {
            this.MER_CP_ORDER = new HashSet<MER_CP_ORDER>();
            this.MER_ORDER_CATEGORY = new HashSet<MER_ORDER_CATEGORY>();
            this.MER_SMV = new HashSet<MER_SMV>();
            this.PRP_DISTTOFACT = new HashSet<PRP_DISTTOFACT>();
            this.PRP_PRODDET = new HashSet<PRP_PRODDET>();
            this.PRP_ASSIGNMAS = new HashSet<PRP_ASSIGNMAS>();
        }
    
        public byte SLNO { get; set; }
        public int ORDSLNO { get; set; }
        public Nullable<int> SKETCHID { get; set; }
        public Nullable<int> SKETCHSLNO { get; set; }
        public Nullable<int> ORDCD { get; set; }
        public string ORDERNO { get; set; }
        public string ORD_REFNO { get; set; }
        public Nullable<short> ORDCOLCD { get; set; }
        public string ORDCOLNM { get; set; }
        public Nullable<short> SIZECD { get; set; }
        public decimal ORDQTY { get; set; }
        public Nullable<decimal> PRDPERCENT { get; set; }
        public decimal PRODQTY { get; set; }
        public Nullable<decimal> UNPRICE { get; set; }
        public Nullable<decimal> TOTPRICE { get; set; }
        public Nullable<decimal> TOTPRICEUSD { get; set; }

        public Nullable<System.DateTime> ORDDATED { get; set; }

        public Nullable<System.DateTime> SHIPDATE { get; set; }
        public string KNITTYPE { get; set; }
        public Nullable<short> YARNCD { get; set; }
        public string YARNDESC { get; set; }
        public decimal YARNQTY { get; set; }
        public Nullable<decimal> PERYARNWATG { get; set; }
        public decimal TOTYARNQTY { get; set; }
        public string SMV_TYPE { get; set; }
        public Nullable<decimal> SMV { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual ICollection<MER_CP_ORDER> MER_CP_ORDER { get; set; }
        public virtual ICollection<MER_ORDER_CATEGORY> MER_ORDER_CATEGORY { get; set; }
        public virtual MER_ORDERCOLOR MER_ORDERCOLOR { get; set; }
        public virtual MER_ORDERMAS MER_ORDERMAS { get; set; }
        public virtual ICollection<MER_SMV> MER_SMV { get; set; }
        public virtual MER_SKETCHDET MER_SKETCHDET { get; set; }
        public virtual ICollection<PRP_DISTTOFACT> PRP_DISTTOFACT { get; set; }
        public virtual ICollection<PRP_PRODDET> PRP_PRODDET { get; set; }
        public virtual ICollection<PRP_ASSIGNMAS> PRP_ASSIGNMAS { get; set; }
        public virtual MER_SIZEINFO MER_SIZEINFO { get; set; }
        public virtual MER_YARNINFO MER_YARNINFO { get; set; }
    }
}
