//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MER_LABDIP
    {
        public short LABCD { get; set; }
        public string LABDIPNO { get; set; }
        public int ORDSLNO { get; set; }
        public int SKETCHID { get; set; }
        public Nullable<int> SKETCHSLNO { get; set; }
        public Nullable<short> YARNCD { get; set; }
        public short COLCD { get; set; }
        public string PANTONNO { get; set; }
        public string SHADE { get; set; }
        public Nullable<System.DateTime> REQDT { get; set; }
        public System.DateTime SENDDT { get; set; }
        public Nullable<System.DateTime> APPDT { get; set; }
        public string STATUS { get; set; }
        public string REMARKS { get; set; }
        public string INSERTBY { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public string INSERTTIME { get; set; }
        public string EDITBY { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public string EDITTIME { get; set; }
    
        public virtual MER_YARNCOLOR MER_YARNCOLOR { get; set; }
    }
}
