//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MER_COMPCODE
    {
        public MER_COMPCODE()
        {
            this.MER_COMPCODE1 = new HashSet<MER_COMPCODE>();
            this.MER_SKETCHMAS = new HashSet<MER_SKETCHMAS>();
            this.MER_ORDERMAS = new HashSet<MER_ORDERMAS>();
        }
    
        public short COMPCD { get; set; }
        public string COMPTYPE { get; set; }
        public string COMPNM { get; set; }
        public string SHORTNM { get; set; }
        public string ADDRS1 { get; set; }
        public string ADDRS2 { get; set; }
        public byte CONCD { get; set; }
        public string POSTCODE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string CONPER { get; set; }
        public Nullable<short> BHCD { get; set; }
        public string STATUS { get; set; }
        public string ATTN { get; set; }
        public string CC { get; set; }
        public string REF { get; set; }
        public string TERRITORY { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual CMN_COUNTRY CMN_COUNTRY { get; set; }
        public virtual ICollection<MER_COMPCODE> MER_COMPCODE1 { get; set; }
        public virtual MER_COMPCODE MER_COMPCODE2 { get; set; }
        public virtual ICollection<MER_SKETCHMAS> MER_SKETCHMAS { get; set; }
        public virtual ICollection<MER_ORDERMAS> MER_ORDERMAS { get; set; }
    }
}
