//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MER_LCREGIS
    {
        public MER_LCREGIS()
        {
            this.MER_ORDERMAS = new HashSet<MER_ORDERMAS>();
        }
    
        public short YEAR { get; set; }
        public int LCSLNO { get; set; }
        public System.DateTime LCDT { get; set; }
        public string LCTYPE { get; set; }
        public string LCNO { get; set; }
        public Nullable<System.DateTime> AMDT { get; set; }
        public short LCCONBANK { get; set; }
        public short LCISSBANK { get; set; }
        public Nullable<short> LCPARTY { get; set; }
        public decimal LCQTY { get; set; }
        public decimal LCAMNT { get; set; }
        public Nullable<System.DateTime> EXPDT { get; set; }
        public Nullable<System.DateTime> SHIPDT { get; set; }
        public Nullable<byte> ATSIGHTDAYS { get; set; }
        public string PRCTYPE { get; set; }
        public string IRCNO { get; set; }
        public string LCANO { get; set; }
        public string REMARKS { get; set; }
        public string ATSIGHTTYPE { get; set; }
        public string INSERTBY { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public string INSERTTIME { get; set; }
        public string EDITBY { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public string EDITTIME { get; set; }
        public string CONTRACTNO { get; set; }
        public Nullable<decimal> LCDISCOUNT { get; set; }
    
        public virtual ICollection<MER_ORDERMAS> MER_ORDERMAS { get; set; }
    }
}
