//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MER_SKETCHMAS
    {
        public MER_SKETCHMAS()
        {
            this.MER_ORDERMAS = new HashSet<MER_ORDERMAS>();
            this.MER_SKETCHDET = new HashSet<MER_SKETCHDET>();
        }
    
        public int SKETCHID { get; set; }
        public string SKETCHNO { get; set; }
        public string STYLENO { get; set; }
        public string ORDERTYPE { get; set; }
        public Nullable<System.DateTime> SKECTHCRDT { get; set; }
        public Nullable<System.DateTime> SKECTHDLDT { get; set; }
        public Nullable<short> COMPCD { get; set; }
        public Nullable<byte> GAUGECD { get; set; }
        public string IMGFLAG { get; set; }
        public string FLAGIMG { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual MER_COMPCODE MER_COMPCODE { get; set; }
        public virtual MER_GAUGE MER_GAUGE { get; set; }
        public virtual ICollection<MER_ORDERMAS> MER_ORDERMAS { get; set; }
        public virtual ICollection<MER_SKETCHDET> MER_SKETCHDET { get; set; }
    }
}
