//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MER_YARNCOLOR
    {
        public MER_YARNCOLOR()
        {
            this.MER_LABDIP = new HashSet<MER_LABDIP>();
        }
    
        public short COLCD { get; set; }
        public string COLNM { get; set; }
    
        public virtual ICollection<MER_LABDIP> MER_LABDIP { get; set; }
    }
}
