//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MER_ORDERMAS
    {
        public MER_ORDERMAS()
        {
            this.MER_CP = new HashSet<MER_CP>();
            this.MER_ORDERDET = new HashSet<MER_ORDERDET>();
        }
    
        public int ORDSLNO { get; set; }
        public Nullable<int> SKETCHID { get; set; }
        public string SKETCHNO { get; set; }
        public Nullable<short> LCYEAR { get; set; }
        public Nullable<int> LCSLNO { get; set; }
        public string STYLENO { get; set; }
        public short COMPCD { get; set; }
        public byte GAUGECD { get; set; }
        public string ORDTYPE { get; set; }
        public string ORDMETHOD { get; set; }
        public Nullable<System.DateTime> ORDDATE { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public string ORDFLAG { get; set; }
        public string STATUS { get; set; }
        public string FLAGIMG { get; set; }
        public string GOODSDESC { get; set; }
        public string REMARKS { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual MER_COMPCODE MER_COMPCODE { get; set; }
        public virtual ICollection<MER_CP> MER_CP { get; set; }
        public virtual MER_GAUGE MER_GAUGE { get; set; }
        public virtual MER_LCREGIS MER_LCREGIS { get; set; }
        public virtual ICollection<MER_ORDERDET> MER_ORDERDET { get; set; }
        public virtual MER_SKETCHMAS MER_SKETCHMAS { get; set; }
    }
}
