//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class PRP_MODULE
    {
        public PRP_MODULE()
        {
            this.PRP_ASSIGNDET = new HashSet<PRP_ASSIGNDET>();
            this.PRP_PRODDET = new HashSet<PRP_PRODDET>();
        }
    
        public int MODCD { get; set; }
        public Nullable<byte> COMPCD { get; set; }
       
        public byte SECCODE { get; set; }
        public int MODULENM { get; set; }
        public string MACTYPE { get; set; }
        public byte GAUGECD { get; set; }
        public short WORKMINTS { get; set; }
        public short MACQTY { get; set; }
        public byte MACEFF { get; set; }
        public int PERDAYMINTS { get; set; }
        public string CATEGORY { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual HRP_COMPUNIT HRP_COMPUNIT { get; set; }
        public virtual HRP_SECTION HRP_SECTION { get; set; }
        public virtual MER_GAUGE MER_GAUGE { get; set; }
        public virtual ICollection<PRP_ASSIGNDET> PRP_ASSIGNDET { get; set; }
        public virtual ICollection<PRP_PRODDET> PRP_PRODDET { get; set; }
    }
}
