//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRP_PRODDET
    {
        public int PRODCD { get; set; }
        public short PRODDETCD { get; set; }
        public byte SLNO { get; set; }
        public int ORDSLNO { get; set; }
        public Nullable<int> MODCD { get; set; }
        public int PRODQTY { get; set; }
        public byte UNITCD { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
        public Nullable<byte> BODY_MC { get; set; }
        public Nullable<byte> NECK_MC { get; set; }
        public string MAC_TYPE { get; set; }
    
        public virtual MER_ORDERDET MER_ORDERDET { get; set; }
        public virtual MER_UNIT MER_UNIT { get; set; }
        public virtual PRP_MODULE PRP_MODULE { get; set; }
        public virtual PRP_PRODMAS PRP_PRODMAS { get; set; }
    }
}
