//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRP_DISTTOFACT
    {
        public PRP_DISTTOFACT()
        {
            this.PRP_ASSIGNMAS = new HashSet<PRP_ASSIGNMAS>();
        }
    
        public int DISTFACTCD { get; set; }
        public byte COMPCD { get; set; }
        public byte SLNO { get; set; }
        public int ORDSLNO { get; set; }
        public string ORD_REFNO { get; set; }
        public byte UNITCD { get; set; }
        public int DISTQTY { get; set; }
        public string ALLOCATE { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual HRP_COMPUNIT HRP_COMPUNIT { get; set; }
        public virtual MER_ORDERDET MER_ORDERDET { get; set; }
        public virtual MER_UNIT MER_UNIT { get; set; }
        public virtual ICollection<PRP_ASSIGNMAS> PRP_ASSIGNMAS { get; set; }
    }
}
