//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRP_ASSIGNMAS
    {
        public PRP_ASSIGNMAS()
        {
            this.PRP_ASSIGNDET = new HashSet<PRP_ASSIGNDET>();
        }
    
        public int ASSIGNCD { get; set; }
        public Nullable<int> DISTFACTCD { get; set; }
        public byte COMPCD { get; set; }
        public byte SECCODE { get; set; }
        public byte SLNO { get; set; }
        public int ORDSLNO { get; set; }
        public short INSERTBY { get; set; }
        public System.DateTime INSERTDT { get; set; }
        public Nullable<short> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDT { get; set; }
    
        public virtual HRP_COMPUNIT HRP_COMPUNIT { get; set; }
        public virtual HRP_SECTION HRP_SECTION { get; set; }
        public virtual MER_ORDERDET MER_ORDERDET { get; set; }
        public virtual ICollection<PRP_ASSIGNDET> PRP_ASSIGNDET { get; set; }
        public virtual PRP_DISTTOFACT PRP_DISTTOFACT { get; set; }
    }
}
